### ISSUE TITLE
Generic Radio Panel option issue

### ISSUE THREAD

**Issue by Rod-Wan** [jdahlblom/DCSFlightpanels#449] opened 2024-01-27 10:46 UTC
When using the current build 4.11.3 I found that the generic radio panel cannot be bound any more. I've traced the last build where it worked correctly to 4.10.4 after that, if you try to use the generic radio panel you cannot bind any controls through software. Interestingly though, if you have a profile with the key strokes already mapped they do work, but cannot be seen or changed.

**Comment by jdahlblom** [comment] 2024-01-28 18:33
OK, will check tomorrow.

**Comment by jdahlblom** [comment] 2024-01-29 12:10
See ```4.11.7``` if the problem is fixed.

**Comment by jdahlblom** [comment] 2024-01-31 15:40
Did it work now? If so pls close this issue.

**Comment by Rod-Wan** [comment] 2024-01-31 19:27
Yes, thank you.

**Closed as completed** 2024-01-31 19:27 UTC
